# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clockWeather.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(0, 0, 120, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton#backButton{\n"
"    border-width: 2px;\n"
"    border-style: none;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(110, 126, 141, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#backButton:pressed{\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"    background-color: rgba(110, 126, 141, 200);\n"
"}\n"
"")
        self.backButton.setObjectName("backButton")
        self.cityPicker = QtWidgets.QComboBox(self.centralwidget)
        self.cityPicker.setGeometry(QtCore.QRect(200, 20, 400, 65))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(25)
        self.cityPicker.setFont(font)
        self.cityPicker.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cityPicker.setStyleSheet("QComboBox#cityPicker{\n"
"    color: rgba(163, 122, 122, 255);\n"
"    background-color: white;\n"
"    selection-background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:drop-down {\n"
"    border-width: 0px;\n"
"}\n"
"\n"
"QComboBox:down-arrow{\n"
"    image: url(noimg); \n"
"    border-width: 0px;\n"
"}\n"
"\n"
"QComboBox#cityPicker:on{ \n"
"    background: white;\n"
"}\n"
"\n"
"QListView{ \n"
"    background-color: white;\n"
"    color: rgba(122, 163, 122, 255);\n"
"}")
        self.cityPicker.setCurrentText("")
        self.cityPicker.setObjectName("cityPicker")
        self.currentIcon = QtWidgets.QLabel(self.centralwidget)
        self.currentIcon.setGeometry(QtCore.QRect(300, 50, 200, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentIcon.sizePolicy().hasHeightForWidth())
        self.currentIcon.setSizePolicy(sizePolicy)
        self.currentIcon.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"}")
        self.currentIcon.setText("")
        self.currentIcon.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/icons/01d.png"))
        self.currentIcon.setScaledContents(True)
        self.currentIcon.setObjectName("currentIcon")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(500, 90, 300, 51))
        self.title.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}")
        self.title.setObjectName("title")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 140, 130, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(122, 163, 122, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 190, 130, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(110, 126, 141, 255);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.currentTemp = QtWidgets.QLabel(self.centralwidget)
        self.currentTemp.setGeometry(QtCore.QRect(660, 140, 100, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTemp.sizePolicy().hasHeightForWidth())
        self.currentTemp.setSizePolicy(sizePolicy)
        self.currentTemp.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.currentTemp.setFont(font)
        self.currentTemp.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: white;\n"
"}")
        self.currentTemp.setObjectName("currentTemp")
        self.currentHumidity = QtWidgets.QLabel(self.centralwidget)
        self.currentHumidity.setGeometry(QtCore.QRect(660, 190, 100, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentHumidity.sizePolicy().hasHeightForWidth())
        self.currentHumidity.setSizePolicy(sizePolicy)
        self.currentHumidity.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.currentHumidity.setFont(font)
        self.currentHumidity.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: white;\n"
"}")
        self.currentHumidity.setObjectName("currentHumidity")
        self.currentDay = QtWidgets.QLabel(self.centralwidget)
        self.currentDay.setGeometry(QtCore.QRect(0, 90, 300, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentDay.sizePolicy().hasHeightForWidth())
        self.currentDay.setSizePolicy(sizePolicy)
        self.currentDay.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(24)
        self.currentDay.setFont(font)
        self.currentDay.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color: rgba(110, 126, 141, 255);\n"
"}")
        self.currentDay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentDay.setObjectName("currentDay")
        self.currentDate = QtWidgets.QLabel(self.centralwidget)
        self.currentDate.setGeometry(QtCore.QRect(0, 140, 300, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentDate.sizePolicy().hasHeightForWidth())
        self.currentDate.setSizePolicy(sizePolicy)
        self.currentDate.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(24)
        self.currentDate.setFont(font)
        self.currentDate.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color: white;\n"
"}")
        self.currentDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentDate.setObjectName("currentDate")
        self.currentWeatherDescription = QtWidgets.QLabel(self.centralwidget)
        self.currentWeatherDescription.setGeometry(QtCore.QRect(0, 190, 300, 50))
        self.currentWeatherDescription.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(18)
        self.currentWeatherDescription.setFont(font)
        self.currentWeatherDescription.setStyleSheet("QLabel{\n"
"    color: rgba(122, 163, 122, 255);\n"
"    background-color:transparent;\n"
"}")
        self.currentWeatherDescription.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentWeatherDescription.setObjectName("currentWeatherDescription")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 310, 760, 10))
        self.line.setStyleSheet("Line{\n"
"    color: white;\n"
"    border-color: white;\n"
"}")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(250, 240, 300, 60))
        self.timeLabel.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(48)
        self.timeLabel.setFont(font)
        self.timeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeLabel.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 330, 761, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.futureTime1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTime1.sizePolicy().hasHeightForWidth())
        self.futureTime1.setSizePolicy(sizePolicy)
        self.futureTime1.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futureTime1.setFont(font)
        self.futureTime1.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: white;\n"
"}")
        self.futureTime1.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTime1.setObjectName("futureTime1")
        self.gridLayout.addWidget(self.futureTime1, 0, 0, 1, 1)
        self.futureTime2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTime2.sizePolicy().hasHeightForWidth())
        self.futureTime2.setSizePolicy(sizePolicy)
        self.futureTime2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futureTime2.setFont(font)
        self.futureTime2.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: white;\n"
"}")
        self.futureTime2.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTime2.setObjectName("futureTime2")
        self.gridLayout.addWidget(self.futureTime2, 0, 2, 1, 1)
        self.futureTime3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTime3.sizePolicy().hasHeightForWidth())
        self.futureTime3.setSizePolicy(sizePolicy)
        self.futureTime3.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futureTime3.setFont(font)
        self.futureTime3.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: white;\n"
"}")
        self.futureTime3.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTime3.setObjectName("futureTime3")
        self.gridLayout.addWidget(self.futureTime3, 0, 4, 1, 1)
        self.futureTime4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTime4.sizePolicy().hasHeightForWidth())
        self.futureTime4.setSizePolicy(sizePolicy)
        self.futureTime4.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futureTime4.setFont(font)
        self.futureTime4.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: white;\n"
"}")
        self.futureTime4.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTime4.setObjectName("futureTime4")
        self.gridLayout.addWidget(self.futureTime4, 0, 6, 1, 1)
        self.futureTime5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTime5.sizePolicy().hasHeightForWidth())
        self.futureTime5.setSizePolicy(sizePolicy)
        self.futureTime5.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futureTime5.setFont(font)
        self.futureTime5.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: white;\n"
"}")
        self.futureTime5.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTime5.setObjectName("futureTime5")
        self.gridLayout.addWidget(self.futureTime5, 0, 8, 1, 1)
        self.futureIcon1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureIcon1.sizePolicy().hasHeightForWidth())
        self.futureIcon1.setSizePolicy(sizePolicy)
        self.futureIcon1.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"}")
        self.futureIcon1.setText("")
        self.futureIcon1.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/icons/01d.png"))
        self.futureIcon1.setScaledContents(True)
        self.futureIcon1.setAlignment(QtCore.Qt.AlignCenter)
        self.futureIcon1.setObjectName("futureIcon1")
        self.gridLayout.addWidget(self.futureIcon1, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.futureIcon2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureIcon2.sizePolicy().hasHeightForWidth())
        self.futureIcon2.setSizePolicy(sizePolicy)
        self.futureIcon2.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"}")
        self.futureIcon2.setText("")
        self.futureIcon2.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/icons/01d.png"))
        self.futureIcon2.setScaledContents(True)
        self.futureIcon2.setObjectName("futureIcon2")
        self.gridLayout.addWidget(self.futureIcon2, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.futureIcon3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureIcon3.sizePolicy().hasHeightForWidth())
        self.futureIcon3.setSizePolicy(sizePolicy)
        self.futureIcon3.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"}")
        self.futureIcon3.setText("")
        self.futureIcon3.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/icons/01d.png"))
        self.futureIcon3.setScaledContents(True)
        self.futureIcon3.setObjectName("futureIcon3")
        self.gridLayout.addWidget(self.futureIcon3, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 1)
        self.futureIcon4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureIcon4.sizePolicy().hasHeightForWidth())
        self.futureIcon4.setSizePolicy(sizePolicy)
        self.futureIcon4.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"}")
        self.futureIcon4.setText("")
        self.futureIcon4.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/icons/01d.png"))
        self.futureIcon4.setScaledContents(True)
        self.futureIcon4.setObjectName("futureIcon4")
        self.gridLayout.addWidget(self.futureIcon4, 1, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 7, 1, 1)
        self.futureIcon5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureIcon5.sizePolicy().hasHeightForWidth())
        self.futureIcon5.setSizePolicy(sizePolicy)
        self.futureIcon5.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"}")
        self.futureIcon5.setText("")
        self.futureIcon5.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/icons/01d.png"))
        self.futureIcon5.setScaledContents(True)
        self.futureIcon5.setObjectName("futureIcon5")
        self.gridLayout.addWidget(self.futureIcon5, 1, 8, 1, 1)
        self.futureTemp1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTemp1.sizePolicy().hasHeightForWidth())
        self.futureTemp1.setSizePolicy(sizePolicy)
        self.futureTemp1.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.futureTemp1.setFont(font)
        self.futureTemp1.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(122, 163, 122, 255);\n"
"}")
        self.futureTemp1.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTemp1.setObjectName("futureTemp1")
        self.gridLayout.addWidget(self.futureTemp1, 2, 0, 1, 1)
        self.futureTemp2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTemp2.sizePolicy().hasHeightForWidth())
        self.futureTemp2.setSizePolicy(sizePolicy)
        self.futureTemp2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.futureTemp2.setFont(font)
        self.futureTemp2.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(122, 163, 122, 255);\n"
"}")
        self.futureTemp2.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTemp2.setObjectName("futureTemp2")
        self.gridLayout.addWidget(self.futureTemp2, 2, 2, 1, 1)
        self.futureTemp3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTemp3.sizePolicy().hasHeightForWidth())
        self.futureTemp3.setSizePolicy(sizePolicy)
        self.futureTemp3.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.futureTemp3.setFont(font)
        self.futureTemp3.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(122, 163, 122, 255);\n"
"}")
        self.futureTemp3.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTemp3.setObjectName("futureTemp3")
        self.gridLayout.addWidget(self.futureTemp3, 2, 4, 1, 1)
        self.futureTemp4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTemp4.sizePolicy().hasHeightForWidth())
        self.futureTemp4.setSizePolicy(sizePolicy)
        self.futureTemp4.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.futureTemp4.setFont(font)
        self.futureTemp4.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(122, 163, 122, 255);\n"
"}")
        self.futureTemp4.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTemp4.setObjectName("futureTemp4")
        self.gridLayout.addWidget(self.futureTemp4, 2, 6, 1, 1)
        self.futureTemp5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futureTemp5.sizePolicy().hasHeightForWidth())
        self.futureTemp5.setSizePolicy(sizePolicy)
        self.futureTemp5.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.futureTemp5.setFont(font)
        self.futureTemp5.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(122, 163, 122, 255);\n"
"}")
        self.futureTemp5.setAlignment(QtCore.Qt.AlignCenter)
        self.futureTemp5.setObjectName("futureTemp5")
        self.gridLayout.addWidget(self.futureTemp5, 2, 8, 1, 1)
        self.futurePrecip1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futurePrecip1.sizePolicy().hasHeightForWidth())
        self.futurePrecip1.setSizePolicy(sizePolicy)
        self.futurePrecip1.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futurePrecip1.setFont(font)
        self.futurePrecip1.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(110, 126, 141, 255);\n"
"}")
        self.futurePrecip1.setAlignment(QtCore.Qt.AlignCenter)
        self.futurePrecip1.setObjectName("futurePrecip1")
        self.gridLayout.addWidget(self.futurePrecip1, 3, 0, 1, 1)
        self.futurePrecip2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futurePrecip2.sizePolicy().hasHeightForWidth())
        self.futurePrecip2.setSizePolicy(sizePolicy)
        self.futurePrecip2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futurePrecip2.setFont(font)
        self.futurePrecip2.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(110, 126, 141, 255);\n"
"}")
        self.futurePrecip2.setAlignment(QtCore.Qt.AlignCenter)
        self.futurePrecip2.setObjectName("futurePrecip2")
        self.gridLayout.addWidget(self.futurePrecip2, 3, 2, 1, 1)
        self.futurePrecip3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futurePrecip3.sizePolicy().hasHeightForWidth())
        self.futurePrecip3.setSizePolicy(sizePolicy)
        self.futurePrecip3.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futurePrecip3.setFont(font)
        self.futurePrecip3.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(110, 126, 141, 255);\n"
"}")
        self.futurePrecip3.setAlignment(QtCore.Qt.AlignCenter)
        self.futurePrecip3.setObjectName("futurePrecip3")
        self.gridLayout.addWidget(self.futurePrecip3, 3, 4, 1, 1)
        self.futurePrecip4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futurePrecip4.sizePolicy().hasHeightForWidth())
        self.futurePrecip4.setSizePolicy(sizePolicy)
        self.futurePrecip4.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futurePrecip4.setFont(font)
        self.futurePrecip4.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(110, 126, 141, 255);\n"
"}")
        self.futurePrecip4.setAlignment(QtCore.Qt.AlignCenter)
        self.futurePrecip4.setObjectName("futurePrecip4")
        self.gridLayout.addWidget(self.futurePrecip4, 3, 6, 1, 1)
        self.futurePrecip5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.futurePrecip5.sizePolicy().hasHeightForWidth())
        self.futurePrecip5.setSizePolicy(sizePolicy)
        self.futurePrecip5.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.futurePrecip5.setFont(font)
        self.futurePrecip5.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"color: rgba(110, 126, 141, 255);\n"
"}")
        self.futurePrecip5.setAlignment(QtCore.Qt.AlignCenter)
        self.futurePrecip5.setObjectName("futurePrecip5")
        self.gridLayout.addWidget(self.futurePrecip5, 3, 8, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 3)
        self.gridLayout.setColumnStretch(5, 1)
        self.gridLayout.setColumnStretch(6, 3)
        self.gridLayout.setColumnStretch(7, 1)
        self.gridLayout.setColumnStretch(8, 3)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 4)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.layoutWidget.raise_()
        self.currentIcon.raise_()
        self.backButton.raise_()
        self.title.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.currentTemp.raise_()
        self.currentHumidity.raise_()
        self.currentDay.raise_()
        self.currentDate.raise_()
        self.currentWeatherDescription.raise_()
        self.line.raise_()
        self.timeLabel.raise_()
        self.cityPicker.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "Home"))
        self.title.setText(_translate("MainWindow", "Current Weather"))
        self.label_3.setText(_translate("MainWindow", "Temperature"))
        self.label_4.setText(_translate("MainWindow", "Humidity"))
        self.currentTemp.setText(_translate("MainWindow", "29 C"))
        self.currentHumidity.setText(_translate("MainWindow", "45%"))
        self.currentDay.setText(_translate("MainWindow", "Monday"))
        self.currentDate.setText(_translate("MainWindow", "23 September 2012"))
        self.currentWeatherDescription.setText(_translate("MainWindow", "Description"))
        self.timeLabel.setText(_translate("MainWindow", "20:01:20"))
        self.futureTime1.setText(_translate("MainWindow", "Time1"))
        self.futureTime2.setText(_translate("MainWindow", "Time1"))
        self.futureTime3.setText(_translate("MainWindow", "Time1"))
        self.futureTime4.setText(_translate("MainWindow", "Time1"))
        self.futureTime5.setText(_translate("MainWindow", "Time1"))
        self.futureTemp1.setText(_translate("MainWindow", "29 C"))
        self.futureTemp2.setText(_translate("MainWindow", "29 C"))
        self.futureTemp3.setText(_translate("MainWindow", "29 C"))
        self.futureTemp4.setText(_translate("MainWindow", "29 C"))
        self.futureTemp5.setText(_translate("MainWindow", "29 C"))
        self.futurePrecip1.setText(_translate("MainWindow", "10 %"))
        self.futurePrecip2.setText(_translate("MainWindow", "10 %"))
        self.futurePrecip3.setText(_translate("MainWindow", "10 %"))
        self.futurePrecip4.setText(_translate("MainWindow", "10 %"))
        self.futurePrecip5.setText(_translate("MainWindow", "10 %"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
