# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PresentUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ClockLabel = QtWidgets.QLabel(self.centralwidget)
        self.ClockLabel.setGeometry(QtCore.QRect(280, 20, 250, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClockLabel.sizePolicy().hasHeightForWidth())
        self.ClockLabel.setSizePolicy(sizePolicy)
        self.ClockLabel.setBaseSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(64)
        font.setKerning(True)
        self.ClockLabel.setFont(font)
        self.ClockLabel.setAutoFillBackground(False)
        self.ClockLabel.setStyleSheet("background: none;\n"
"color: white;")
        self.ClockLabel.setScaledContents(False)
        self.ClockLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ClockLabel.setObjectName("ClockLabel")
        self.ClockLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ClockLabel_2.setGeometry(QtCore.QRect(20, 90, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(32)
        self.ClockLabel_2.setFont(font)
        self.ClockLabel_2.setAutoFillBackground(False)
        self.ClockLabel_2.setStyleSheet("QLabel{\n"
"    background: none; \n"
"    color: white;\n"
"}")
        self.ClockLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ClockLabel_2.setObjectName("ClockLabel_2")
        self.ClockLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.ClockLabel_3.setGeometry(QtCore.QRect(20, 40, 250, 70))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(32)
        self.ClockLabel_3.setFont(font)
        self.ClockLabel_3.setAutoFillBackground(False)
        self.ClockLabel_3.setStyleSheet("QLabel{\n"
"background: none; \n"
"color:rgba(110, 126, 141, 255);\n"
"}")
        self.ClockLabel_3.setScaledContents(False)
        self.ClockLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ClockLabel_3.setObjectName("ClockLabel_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 220, 760, 10))
        self.line.setStyleSheet("background: white;\n"
"border: white;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 20, 760, 10))
        self.line_2.setStyleSheet("background: white; \n"
"border: 0.5px solid white;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.TempLabel = QtWidgets.QLabel(self.centralwidget)
        self.TempLabel.setGeometry(QtCore.QRect(500, 150, 201, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TempLabel.sizePolicy().hasHeightForWidth())
        self.TempLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.TempLabel.setFont(font)
        self.TempLabel.setStyleSheet("QLabel{\n"
"    background: transparent;\n"
"    color: rgba(122, 163, 122, 255);\n"
"}")
        self.TempLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TempLabel.setWordWrap(True)
        self.TempLabel.setObjectName("TempLabel")
        self.TempValue = QtWidgets.QLabel(self.centralwidget)
        self.TempValue.setGeometry(QtCore.QRect(710, 150, 71, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TempValue.sizePolicy().hasHeightForWidth())
        self.TempValue.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.TempValue.setFont(font)
        self.TempValue.setStyleSheet("QLabel{\n"
"    background: transparent;\n"
"    color: white;\n"
"}")
        self.TempValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TempValue.setObjectName("TempValue")
        self.RainLabel = QtWidgets.QLabel(self.centralwidget)
        self.RainLabel.setGeometry(QtCore.QRect(550, 10, 111, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RainLabel.sizePolicy().hasHeightForWidth())
        self.RainLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        self.RainLabel.setFont(font)
        self.RainLabel.setStyleSheet("QLabel{\n"
"    background: transparent;\n"
"    color: rgba(110, 126, 141, 255);\n"
"}")
        self.RainLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RainLabel.setWordWrap(False)
        self.RainLabel.setObjectName("RainLabel")
        self.WeatherPic = QtWidgets.QLabel(self.centralwidget)
        self.WeatherPic.setGeometry(QtCore.QRect(590, 50, 150, 150))
        self.WeatherPic.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"}")
        self.WeatherPic.setText("")
        self.WeatherPic.setPixmap(QtGui.QPixmap("../../../../.designer/backup/icons/01d.png"))
        self.WeatherPic.setScaledContents(True)
        self.WeatherPic.setObjectName("WeatherPic")
        self.RainValue = QtWidgets.QLabel(self.centralwidget)
        self.RainValue.setGeometry(QtCore.QRect(670, 10, 110, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RainValue.sizePolicy().hasHeightForWidth())
        self.RainValue.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.RainValue.setFont(font)
        self.RainValue.setStyleSheet("QLabel{\n"
"    background: transparent;\n"
"    color: white;\n"
"}")
        self.RainValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RainValue.setWordWrap(True)
        self.RainValue.setObjectName("RainValue")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 240, 761, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ClockWeather = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClockWeather.sizePolicy().hasHeightForWidth())
        self.ClockWeather.setSizePolicy(sizePolicy)
        self.ClockWeather.setMaximumSize(QtCore.QSize(16777215, 16777209))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.ClockWeather.setFont(font)
        self.ClockWeather.setStyleSheet("QPushButton{\n"
"    background-color: rgba(122, 163, 122, 255);\n"
"    color: white;\n"
"    border-style: solid;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color:  rgba(122, 163, 122, 200);\n"
"}")
        self.ClockWeather.setObjectName("ClockWeather")
        self.gridLayout.addWidget(self.ClockWeather, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.Timer = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Timer.sizePolicy().hasHeightForWidth())
        self.Timer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.Timer.setFont(font)
        self.Timer.setStyleSheet("QPushButton{\n"
"    background-color: rgba(122, 163, 122, 255);\n"
"    color: white;\n"
"    border-style: solid;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color:  rgba(122, 163, 122, 200);\n"
"}")
        self.Timer.setObjectName("Timer")
        self.gridLayout.addWidget(self.Timer, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.Radio = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Radio.sizePolicy().hasHeightForWidth())
        self.Radio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.Radio.setFont(font)
        self.Radio.setAutoFillBackground(False)
        self.Radio.setStyleSheet("QPushButton{\n"
"    background-color: rgba(122, 163, 122, 255);\n"
"    color: white;\n"
"    border-style: solid;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color:  rgba(122, 163, 122, 200);\n"
"}")
        self.Radio.setObjectName("Radio")
        self.gridLayout.addWidget(self.Radio, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 4, 1, 1)
        self.PhotoFrame = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PhotoFrame.sizePolicy().hasHeightForWidth())
        self.PhotoFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.PhotoFrame.setFont(font)
        self.PhotoFrame.setStyleSheet("QPushButton{\n"
"    background-color: rgba(122, 163, 122, 255);\n"
"    color: white;\n"
"    border-style: solid;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color:  rgba(122, 163, 122, 200);\n"
"}")
        self.PhotoFrame.setObjectName("PhotoFrame")
        self.gridLayout.addWidget(self.PhotoFrame, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)
        self.PlateReader = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlateReader.sizePolicy().hasHeightForWidth())
        self.PlateReader.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.PlateReader.setFont(font)
        self.PlateReader.setStyleSheet("QPushButton{\n"
"    background-color: rgba(122, 163, 122, 255);\n"
"    color: white;\n"
"    border-style: solid;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color:  rgba(122, 163, 122, 200);\n"
"}")
        self.PlateReader.setObjectName("PlateReader")
        self.gridLayout.addWidget(self.PlateReader, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 3, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(110, 126, 141, 255);\n"
"    color: white;\n"
"    border-style: solid;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rrgba(110, 126, 141, 200);\n"
"}")
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 2, 4, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 2)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 3)
        self.locationLabel = QtWidgets.QLabel(self.centralwidget)
        self.locationLabel.setGeometry(QtCore.QRect(305, 140, 200, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationLabel.sizePolicy().hasHeightForWidth())
        self.locationLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(20)
        self.locationLabel.setFont(font)
        self.locationLabel.setStyleSheet("QLabel{\n"
"    background: transparent;\n"
"    color: white;\n"
"}")
        self.locationLabel.setScaledContents(False)
        self.locationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.locationLabel.setObjectName("locationLabel")
        self.ClockLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.ClockLabel_4.setGeometry(QtCore.QRect(20, 150, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(32)
        self.ClockLabel_4.setFont(font)
        self.ClockLabel_4.setAutoFillBackground(False)
        self.ClockLabel_4.setStyleSheet("QLabel{\n"
"    background: none; \n"
"    color: rgba(122, 163, 122, 255);\n"
"}")
        self.ClockLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ClockLabel_4.setObjectName("ClockLabel_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ClockLabel.setText(_translate("MainWindow", "20:00"))
        self.ClockLabel_2.setText(_translate("MainWindow", "<html><head/><body><p>18 October</p></body></html>"))
        self.ClockLabel_3.setText(_translate("MainWindow", "<html><head/><body><p>Wednesday</p></body></html>"))
        self.TempLabel.setText(_translate("MainWindow", "Current Temp"))
        self.TempValue.setText(_translate("MainWindow", "29 C"))
        self.RainLabel.setText(_translate("MainWindow", "Rain"))
        self.RainValue.setText(_translate("MainWindow", "0.0 mm"))
        self.ClockWeather.setText(_translate("MainWindow", "Clock/ \n"
" Weather"))
        self.Timer.setText(_translate("MainWindow", "Timer"))
        self.Radio.setText(_translate("MainWindow", "Radio"))
        self.PhotoFrame.setText(_translate("MainWindow", "Photo\n"
" Frame"))
        self.PlateReader.setText(_translate("MainWindow", "Plate\n"
"Reader"))
        self.closeButton.setText(_translate("MainWindow", "Close \n"
"Application"))
        self.locationLabel.setText(_translate("MainWindow", "London"))
        self.ClockLabel_4.setText(_translate("MainWindow", "<html><head/><body><p>2022</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
