# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background: black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(0, 0, 120, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton#backButton{\n"
"    border-width: 2px;\n"
"    border-style: none;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(110, 126, 141, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#backButton:pressed{\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"    background-color: rgba(110, 126, 141, 200);\n"
"}\n"
"")
        self.backButton.setObjectName("backButton")
        self.pictureFrameLabel = QtWidgets.QLabel(self.centralwidget)
        self.pictureFrameLabel.setGeometry(QtCore.QRect(0, 0, 800, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureFrameLabel.sizePolicy().hasHeightForWidth())
        self.pictureFrameLabel.setSizePolicy(sizePolicy)
        self.pictureFrameLabel.setText("")
        self.pictureFrameLabel.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/imgs/dog.jpg"))
        self.pictureFrameLabel.setScaledContents(True)
        self.pictureFrameLabel.setObjectName("pictureFrameLabel")
        self.rightPicButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightPicButton.setGeometry(QtCore.QRect(400, 40, 395, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightPicButton.sizePolicy().hasHeightForWidth())
        self.rightPicButton.setSizePolicy(sizePolicy)
        self.rightPicButton.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"border: 0px;\n"
"}")
        self.rightPicButton.setText("")
        self.rightPicButton.setObjectName("rightPicButton")
        self.leftPicButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftPicButton.setGeometry(QtCore.QRect(0, 40, 395, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftPicButton.sizePolicy().hasHeightForWidth())
        self.leftPicButton.setSizePolicy(sizePolicy)
        self.leftPicButton.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"border: 0px;\n"
"}")
        self.leftPicButton.setText("")
        self.leftPicButton.setObjectName("leftPicButton")
        self.pictureFrameLabel.raise_()
        self.backButton.raise_()
        self.leftPicButton.raise_()
        self.rightPicButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
