# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(0, 0, 120, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton#backButton{\n"
"    border-width: 2px;\n"
"    border-style: none;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(110, 126, 141, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#backButton:pressed{\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"    background-color: rgba(110, 126, 141, 200);\n"
"}\n"
"")
        self.backButton.setObjectName("backButton")
        self.startTimer = QtWidgets.QPushButton(self.centralwidget)
        self.startTimer.setGeometry(QtCore.QRect(60, 490, 200, 71))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.startTimer.setFont(font)
        self.startTimer.setStyleSheet("QPushButton{\n"
"    background-color: rgba(122, 163, 122, 255);\n"
"    color: white;\n"
"    border-style: solid;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color:  rgba(122, 163, 122, 200);\n"
"}\n"
"")
        self.startTimer.setObjectName("startTimer")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(200, 70, 400, 120))
        self.frame.setStyleSheet("QFrame{\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    border-radius:5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 0, 400, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setStyleSheet("QLCDNumber{\n"
"    border: white;\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}")
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(60, 220, 670, 251))
        self.frame_2.setStyleSheet("QFrame{\n"
"    border: 2px solid white;\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(30, 10, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    border: 0px black none;\n"
"    color: white;\n"
"    background-color: transparent;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.timerDialSecs = QtWidgets.QDial(self.frame_2)
        self.timerDialSecs.setGeometry(QtCore.QRect(470, 40, 200, 200))
        self.timerDialSecs.setStyleSheet("QDial{\n"
"    background: transparent;\n"
"}")
        self.timerDialSecs.setMaximum(59)
        self.timerDialSecs.setObjectName("timerDialSecs")
        self.timerDialMins = QtWidgets.QDial(self.frame_2)
        self.timerDialMins.setGeometry(QtCore.QRect(240, 40, 200, 200))
        self.timerDialMins.setStyleSheet("QDial{\n"
"    background: transparent;\n"
"}")
        self.timerDialMins.setMaximum(59)
        self.timerDialMins.setObjectName("timerDialMins")
        self.timerDialHours = QtWidgets.QDial(self.frame_2)
        self.timerDialHours.setGeometry(QtCore.QRect(10, 40, 200, 200))
        self.timerDialHours.setStyleSheet("QDial{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QDial::handle{\n"
"    color: red;\n"
"}")
        self.timerDialHours.setObjectName("timerDialHours")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(260, 10, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    border: 0px black none;\n"
"    color: white;\n"
"    background-color: transparent;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(490, 10, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    border: 0px black none;\n"
"    color: white;\n"
"    background-color: transparent;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.resetTimer = QtWidgets.QPushButton(self.centralwidget)
        self.resetTimer.setGeometry(QtCore.QRect(295, 490, 200, 71))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.resetTimer.setFont(font)
        self.resetTimer.setStyleSheet("QPushButton{\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(110, 126, 141, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"    background-color: rgba(110, 126, 141, 200);\n"
"}\n"
"")
        self.resetTimer.setObjectName("resetTimer")
        self.pomoTimer = QtWidgets.QPushButton(self.centralwidget)
        self.pomoTimer.setGeometry(QtCore.QRect(530, 490, 200, 71))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.pomoTimer.setFont(font)
        self.pomoTimer.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-style: none;\n"
"    border-color: black;\n"
"    border-radius: 10px;\n"
"    border-width: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: white;\n"
"}\n"
"")
        self.pomoTimer.setObjectName("pomoTimer")
        self.frame_2.raise_()
        self.backButton.raise_()
        self.startTimer.raise_()
        self.frame.raise_()
        self.resetTimer.raise_()
        self.pomoTimer.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "Home"))
        self.startTimer.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Hours"))
        self.label_2.setText(_translate("MainWindow", "Minutes"))
        self.label_3.setText(_translate("MainWindow", "Seconds"))
        self.resetTimer.setText(_translate("MainWindow", "Reset"))
        self.pomoTimer.setText(_translate("MainWindow", "Pomodoro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
